# Generated by Django 4.2.3 on 2023-07-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='passport',
            field=models.TextField(null=True),
        ),
    ]
