# Generated by Django 4.2.3 on 2023-07-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_alter_users_referral_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bonus',
            field=models.FloatField(default=0.0),
        ),
    ]
